version: '3.8'

services:
  backend:
    build:
      context: ./FarmXChain
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/railway
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8080
      - SERVER_SERVLET_CONTEXT_PATH=/api/v1
    networks:
      - farmxchain-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8080/api/v1
    networks:
      - farmxchain-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=railway
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - farmxchain-network

volumes:
  mysql-data:


networks:
  farmxchain-network:
    driver: bridge
