services:
  - type: web
    name: farmxchain-backend
    runtime: java
    buildCommand: cd FarmXChain && mvn clean package -DskipTests
    startCommand: java -jar target/FarmXChain-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://maglev.proxy.rlwy.net:35964/railway
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: vPPJESNgSSHhvfMdOBPcEOxySHPhVOLi
      - key: SERVER_PORT
        value: "8080"
      - key: SERVER_SERVLET_CONTEXT_PATH
        value: /api/v1
